# Site settings
title: Quoc-Duong Nguyen
email: nguyenquocduongqnu@gmail.com
description: Machine learning
baseurl: ""
url: "https://nguyenquocduongqnu.github.io/"
github_username:  nguyenquocduongqnu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
